apiVersion: apps/v1
kind: Deployment
metadata:
  name: yamifooddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yamifood
  template:
    metadata:
      labels:
        app: yamifood
    spec:
      containers:
        - name: yamifoodcontainer
          image: techsriman/yamifood:3.0
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
